### ISSUE TITLE
OrgSecret list shows all organizations

### ISSUE THREAD

**Issue by CubicNitrous** [drone/drone-cli#131]
```bash
drone orgsecret ls <ORG_NAME>
```

This returns all secrets regardless of Org.  Shouldn't it only return the org I specified?

Using version 1.1.0

**Comment by bradrydzewski** [comment]
This is the expected behavior at the moment. The `drone orgsecret ls` command does not currently take any arguments and invokes the `OrgSecretListAll` [1] function to list all secrets for all organizations. We could enhance this command to optionally filter the list if an organization is provided, using the `OrgSecretList` [2] function which takes an organization as an argument

[1] https://github.com/drone/drone-cli/blob/master/drone/orgsecret/secret_list.go#L33
[2] https://github.com/drone/drone-go/blob/master/drone/client.go#L407

**Comment by CubicNitrous** [comment]
With our github enterprise having hundreds of orgs I would really like to see that option :)

**Comment by bradrydzewski** [comment]
we added a `--filter` flag and tagged a v1.1.2 release. You can do `drone secret ls --filter=<org>`

**Comment by CubicNitrous** [comment]
Works great thanks @bradrydzewski !
